compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
mixed_precision: "no"
num_machines: 1
machine_rank: 0
num_processes: 1
main_training_function: main
use_cpu: false
gpu_ids: all
dynamo_backend: "no"